#!/bin/sh

if [ -e "/etc/config/ucitrack" ]; then
	uci -q batch <<-EOF
		delete ucitrack.@passwall2_server[-1]
		add ucitrack passwall2_server
		set ucitrack.@passwall2_server[-1].init=passwall2_server
		commit ucitrack
EOF
fi

lua /usr/lib/lua/luci/passwall2/server_app.lua migrate >/dev/null 2>&1

rm -f /tmp/luci-indexcache /tmp/luci-indexcache.*
rm -rf /tmp/luci-modulecache/
killall -HUP rpcd 2>/dev/null

exit 0
